#!/bin/sh 
# Take screenshot and then upload it to Teknik using gone
# (c) arcetera 2015 - wtfpl
# requires: maim, slop, gone

tmpfile="$TMPDIR/$(date +%s).png"

case $1 in
	-s) maim -s $tmpfile ;;
	-f) maim $tmpfile ;;
	*)
		printf '%s\n' "Usage: left [-sf]"
		exit 1
	;;
esac

gone $tmpfile
